auth0/auth0-flutter

- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/ClearCredentialsRequestHandlerTest.kt
The `clearCredentials` method on Android Credentials Manager handler always returns `true`, same as `hasValidCredentials`, but the assertion in the test is different. This PR aligns them.
> chore: update ClearCredentials test assertion to be consistent with HasValidCredentials

- .circleci/config.yml
- auth0_flutter/CHANGELOG.md
- auth0_flutter/pubspec.yaml
- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
This sets up the changelog for both packages to reflect the 1.0.0-beta.1 release, as well as some changes in the pubspec.yml files.
This will allow me to publish `auth0_flutter_platform_interface`; a release PR for `auth0_flutter` will follow shortly after.
> Prepare auth0_flutter_platform_interface 1.0.0-beta.1 for publishing

- auth0_flutter/README.md
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LoginWebAuthRequestHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/LoginWebAuthRequestHandlerTest.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandlerTest.kt
- auth0_flutter/example/ios/Tests/AuthAPI/AuthAPILoginUsernameOrEmailMethodHandlerTests.swift
- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerSpies.swift
- auth0_flutter/example/ios/Tests/WebAuth/WebAuthLoginMethodHandlerTests.swift
- auth0_flutter/ios/Classes/AuthAPI/AuthAPILoginUsernameOrEmailMethodHandler.swift
- auth0_flutter/ios/Classes/WebAuth/WebAuthLoginMethodHandler.swift
- auth0_flutter/lib/src/authentication_api.dart
- auth0_flutter/lib/src/web_authentication.dart
- auth0_flutter/test/authentication_api_test.dart
- auth0_flutter/test/web_authentication_test.dart
This PR moves the default scope value from the native SDK layer to the Dart layer, and updates it to be `openid profile email offline_access`. 
Previously, the default scope value was set by Auth0.Android and Auth0.swift, and was equal to `openid profile email`. This meant that the native wrapper code would not pass along any empty scope values received from the Dart layer, to allow that default value to be set by Auth0.Android and Auth0.swift. Now, the Dart layer is setting the default scope value, so we pass along the received value as-is to Auth0.Android and Auth0.swift. These native SDKs will make sure to add `openid` to any received scope value that does not already have it, even if it's empty. 
The unit tests were updated, and also the changes were tested manually using an iPhone 13 …
> Add `offline_access` to the default scope [SDK-3435]

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/RenewApiRequestHandler.kt
This PR fixes an issue where the Login and Renew handlers from the Android Auth API client were returning the wrong key for the token type, causing an error in the Dart code. `type` was the key being returned by these handlers, while the Dart code [expected](https://github.com/auth0/auth0-flutter/blob/first-availability/auth0_flutter_platform_interface/lib/src/credentials.dart#L62) `tokenType`. 
This was found while manually testing the changes in https://github.com/auth0/auth0-flutter/pull/112.
> Fix token type key in Kotlin handlers

- .circleci/config.yml
This PR uses the `current` CircleCI Docker image instead of the `2022.04`, so it's always up-to-date.
> Use current Circle image

- .github/ISSUE_TEMPLATE/Bug Report.yml
- .github/ISSUE_TEMPLATE/Feature Request.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds GitHub [form issues](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) for feature requests and bug reports, and a pull request template.
> Add GitHub templates [SDK-3493]

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/HasValidCredentialsRequestHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/HasValidCredentialsRequestHandlerTest.kt
This fixes an issue where `minTtl` is sent as an argument for `hasValidCredentials` as an `int`, but on Android this wrongly expects a `Long`.
It also fixes up a few cases where `val` could safely be used for immutability.
Unit tests updated to match new requirements.
> fix(android): hasValidCredentials accepts minTtl as int

- auth0_flutter/example/lib/example_app.dart
This PR removes `useCredentialsManager: false` from the example app, now that both Credentials Manager implementations were merged.
> Enable the Credentials Manager in the example app

- auth0_flutter/lib/src/credentials_manager.dart
- auth0_flutter/lib/src/web_authentication.dart
- auth0_flutter/test/credentials_manager_test.dart
- auth0_flutter/test/web_authentication_test.dart
- auth0_flutter/test/web_authentication_test.mocks.dart
This PR renames the following Credentials Manager methods:
- `get()` to `credentials()`
- `set()` to `storeCredentials()`
- `clear()` to `clearCredentials()`
The `hasValidCredentials()` method was left as-is.
In the case of `get()`, the Dart design guidelines instruct (1) to [avoid starting a method name](https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get) with `get`, and (2) to [have the code read like a sentence](https://dart.dev/guides/language/effective-dart/design#consider-making-the-code-read-like-a-sentence). 
Previously, getting credentials required the following code:
```dart
final credentials = await auth0.webAuthentication.credentialsManager.get() // Get what?
```
Now it changes to:
```dart
final credentials = await …
```
> Have the Credentials Manager API follow the Dart design guidelines

- auth0_flutter/ios/Classes/Extensions.swift
- auth0_flutter/ios/auth0_flutter.podspec
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
The errors `isPasswordLeaked`, `isLoginRequired`, and `isNetworkError` were recently added to Auth0.swift. The changes are now out in the [2.2.0](https://github.com/auth0/Auth0.swift/releases/tag/2.2.0) release.
This PR raises the minimum Auth0.swift version to 2.2.0, and removes the `Auth0APIError` extension from the Swift code in the Flutter SDK, as it's not needed anymore.
> Remove `Auth0APIError` extension [SDK-3498]

- README.md
- auth0_flutter/example/README.md
- auth0_flutter/lib/src/authentication_api.dart
- auth0_flutter_platform_interface/README.md
- auth0_flutter_platform_interface/lib/src/credentials.dart
This PR applies the word list from the Docs team to the READMEs and the API docs.
> Apply word list to READMEs and API docs

- auth0_flutter/lib/auth0_flutter.dart
This PR exports the `DatabaseUser` type, which was not exported.
> Export `DatabaseUser` [SDK-3504]

- auth0_flutter_platform_interface/lib/src/credentials-manager/options/local_authentication_options.dart
This PR has the `LocalAuthenticationOptions` constructor be a `const` constructor, like the one of the analogous `IdTokenValidationConfig`.
> Make `LocalAuthenticationOptions` constructor `const`

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/Auth0FlutterAuthMethodCallHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/Auth0FlutterPlugin.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/Auth0FlutterWebAuthMethodCallHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/CredentialsManagerMethodCallHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/UserProfileExtensions.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/MethodCallRequest.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/ApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/RenewApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/ResetPasswordApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/SignupApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/UserInfoApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/ClearCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/GetCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/HasValidCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LoginWebAuthRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LogoutWebAuthRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/utils/assertHasProperties.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/utils/getCustomClaims.kt
This PR fixes the most innocuous warnings reported by Android Studio:
- Unused imports
- Semicolons
- Usage of `var` for values that are never modified (instead of `val`)
The remaining warnings were left untouched, for example:
> Fix most Android warnings

- .circleci/config.yml
- auth0_flutter/example/ios/.slather.yml
- auth0_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerExtensionsTests.swift
- auth0_flutter/example/ios/Tests/ExtensionsTests.swift
- auth0_flutter/example/ios/Tests/Utilities.swift
This PR fixes the iOS coverage reporting:
> Fix iOS coverage reporting

- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerExtensionsTests.swift
- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerGetMethodHandlerTests.swift
- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerHasValidMethodHandlerTests.swift
- auth0_flutter/ios/Classes/CredentialsManager/CredentialsManagerClearMethodHandler.swift
- auth0_flutter/ios/Classes/CredentialsManager/CredentialsManagerExtensions.swift
- auth0_flutter/ios/Classes/CredentialsManager/CredentialsManagerGetMethodHandler.swift
- auth0_flutter/ios/Classes/CredentialsManager/CredentialsManagerHasValidMethodHandler.swift
- auth0_flutter/ios/Classes/CredentialsManager/CredentialsManagerSaveMethodHandler.swift
- auth0_flutter/ios/auth0_flutter.podspec
This PR updates Auth0.swift to 2.3.0, and sets it as the minimum required version.
> Update Auth0.swift to 2.3.0

- README.md
- auth0_flutter/README.md
- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerHandlerTests.swift
- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerHasValidMethodHandlerTests.swift
- auth0_flutter/ios/Classes/CredentialsManager/CredentialsManagerHandler.swift
- auth0_flutter_platform_interface/README.md
The current implementation of the iOS Credentials Manager will create a new instance every time a Credentials Manager method is called from Dart code. This PR makes sure only a single instance is used.
> Keep a single instance of iOS Credentials Manager [SDK-3519]

- auth0_flutter/example/lib/example_app.dart
- auth0_flutter/lib/auth0_flutter.dart
- auth0_flutter/lib/src/web_authentication.dart
⚠️ **This PR contains breaking changes**
Currently, Web Auth methods (login and logout) take a `scheme` parameter separately. Unlike the rest of the parameters, this one is not specific to each Web Auth method, but is something that applies to Web Auth in general (in Android). One would never specify a different value for `login()` than for `logout()`.
Thus this parameter belongs to the Web Auth instance itself. `webAuthentication()` already takes a `useCredentialsManager` parameter for the same reasons. So having `scheme` in `login()` and `logout()` would be inconsistent, and become a potential source of confusion.
This PR moves `scheme` out of `login()` and `logout()`, up into `webAuthentication()`.
**Before/after (usage)**
> Move `scheme` to `webAuthentication()`

- auth0_flutter/lib/auth0_flutter.dart
- auth0_flutter/lib/src/credentials_manager.dart
- auth0_flutter/lib/src/web_authentication.dart
- auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
- auth0_flutter_platform_interface/lib/src/credentials-manager/options/local_authentication.dart
- auth0_flutter_platform_interface/lib/src/request/request.dart
- auth0_flutter_platform_interface/test/method_channel_credentials_manager_test.dart
⚠️ **This PR contains breaking changes**
This PR renames the `LocalAuthenticationOptions` class to just `LocalAuthentication`. This class is used as follows:
```dart
const options =
LocalAuthenticationOptions(title: 'Please authenticate to continue');
final auth0 = Auth0('YOUR_AUTH0_DOMAIN', 'YOUR_AUTH0_CLIENT_ID',
localAuthentication: options);
final credentials = await auth0.credentialsManager.credentials();
```
Setting it will enable the local authentication feature, which is disabled by default. So it's actually modeling the local authentication feature itself, instead of simply holding settings for a feature that is already in use. As such, it should be called just `LocalAuthentication`, without the `Options` suffix.
Compare it to the `IdTokenValidationConfig` class, which is used as …
> Rename `LocalAuthenticationOptions` to `LocalAuthentication`

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
This is the General Availability release of the **Auth0 Flutter SDK**! 🎉
This release marks the first stable release of the SDK and is fully supported for use in production environments.
There are a small number of breaking changes from `1.0.0-fa.0` in this release:
**Renamed properties**
The following properties were renamed to comply with [Dart's API guidelines](https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words).
See #146
- `UserProfile.profileURL` to `UserProfile.profileUrl`
- `UserProfile.pictureURL` to `UserProfile.pictureUrl`
- `UserProfile.websiteURL` to `UserProfile.websiteUrl`
- `ApiException.isInvalidAuthorizeURL` to `ApiException.isInvalidAuthorizeUrl`
- `ApiException.isPKCENotAvailable` to …
> afpi: Release 1.0.0

- auth0_flutter/pubspec.lock
- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
This is the General Availability release of the **Auth0 Flutter SDK**! 🎉
This release marks the first stable release of the SDK and is fully supported for use in production environments.
There are a small number of breaking changes from `1.0.0-fa.0` in this release:
**Renamed properties**
The following properties were renamed to comply with [Dart's API guidelines](https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words).
See #146
- `UserProfile.profileURL` to `UserProfile.profileUrl`
- `UserProfile.pictureURL` to `UserProfile.pictureUrl`
- `UserProfile.websiteURL` to `UserProfile.websiteUrl`
- `ApiException.isInvalidAuthorizeURL` to `ApiException.isInvalidAuthorizeUrl`
- `ApiException.isPKCENotAvailable` to …
> afpi: Release 1.0.1 (GA)

- auth0_flutter/CHANGELOG.md
- auth0_flutter/lib/src/version.dart
- auth0_flutter/pubspec.lock
- auth0_flutter/pubspec.yaml
This is the General Availability release of the **Auth0 Flutter SDK**! 🎉
This release marks the first stable release of the SDK and is fully supported for use in production environments.
There are a small number of breaking changes from `1.0.0-fa.0` in this release:
**Renamed properties**
The following properties were renamed to comply with [Dart's API guidelines](https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words).
See #146
- `UserProfile.profileURL` to `UserProfile.profileUrl`
- `UserProfile.pictureURL` to `UserProfile.pictureUrl`
- `UserProfile.websiteURL` to `UserProfile.websiteUrl`
- `ApiException.isInvalidAuthorizeURL` to `ApiException.isInvalidAuthorizeUrl`
- `ApiException.isPKCENotAvailable` to …
> af: Release 1.0.0

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandlerTest.kt
The Android `SaveCredentialsRequestHandler` receives an `expiresAt` UTC string date from the Dart layer. This date string should be parsed as UTC, but instead it gets parsed using the default timezone. Thus, the default timezone's offset gets added to the date, resulting in an incorrect `Credentials.expiresAt` value.
This happens because no timezone was specified for the `SimpleDateFormat` parser, and as such `TimeZone.getDefault()` gets used by default.
This PR ensures the `SaveCredentialsRequestHandler` parses this date as UTC, by setting "UTC" as the parser's timezone.
Fixes https://github.com/auth0/auth0-flutter/issues/160
Asserts were added to an existing unit test.
> Fix timezone issue in Android Credentials Manager handler

- auth0_flutter/.shiprc
- auth0_flutter/ios/auth0_flutter.podspec
This PR updates the version number in the Podspec, which was still `1.0.0-fa.0`, and formats it. Even though we don't publish this Podspec to Cocoapods, that version number still shows up on the console when the developer runs `pod install`. So it must show the current version number.
The .shiprc file was updated as well so the version number in the Podspec gets bumped when creating a new release PR.
> af: Update Podspec

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/Auth0FlutterAuthMethodCallHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/RenewApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/ResetPasswordApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/SignupApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/UserInfoApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/GetCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LoginWebAuthRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LogoutWebAuthRequestHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandlerTest.kt
This PR removes or replaces all usages of the `getOrDefault()` on the Kotlin code, as this method is only available on Android API 24+: https://developer.android.com/reference/java/util/Map#getOrDefault(java.lang.Object,%20V)
For the cases where there was a non-null default value, the Elvis operator was used to provide the default value.
For the cases where the default value was simply `null`, there was no need to do anything else as the map already returns `null` if the value is not present:
Also, an unused import was removed.
Fixes https://github.com/auth0/auth0-flutter/issues/178
> af: Replace usages of `getOrDefault()`

- auth0_flutter/android/build.gradle
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/UserProfileExtensions.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginWithOtpApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/RenewApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/GetCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LoginWebAuthRequestHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/UserProfileExtensionsTest.kt
`auth0-flutter` does claims parsing independently from `Auth0.Android`. This causes issues that have been handled on the Android side. To fix this we use `UserProfile` from `Auth0.Android` instead of recreating it.
https://github.com/auth0/auth0-flutter/issues/186
This has been tested manually. Since the changes are consumed from `Auth0.Android` there is no need for coverage.
> af: Fix Apple login connection crash in Android

- auth0_flutter/FAQ.md
- auth0_flutter/example/ios/Flutter/AppFrameworkInfo.plist
- auth0_flutter/example/ios/Podfile
- auth0_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- auth0_flutter/example/ios/Runner/AppDelegate.swift
- auth0_flutter/example/ios/Runner/Base.lproj/Main.storyboard
- auth0_flutter/example/ios/Runner/Info.plist
- auth0_flutter/example/ios/Tests/WebAuth/WebAuthLoginMethodHandlerTests.swift
- auth0_flutter/example/ios/Tests/WebAuth/WebAuthSpies.swift
- auth0_flutter/example/lib/example_app.dart
- auth0_flutter/ios/Classes/WebAuth/WebAuthExtensions.swift
- auth0_flutter/ios/Classes/WebAuth/WebAuthLoginMethodHandler.swift
- auth0_flutter/ios/Classes/WebAuth/WebAuthModels.swift
- auth0_flutter/lib/auth0_flutter.dart
- auth0_flutter/lib/src/web_authentication.dart
- auth0_flutter/pubspec.lock
- auth0_flutter/test/web_authentication_test.dart
- auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
- auth0_flutter_platform_interface/lib/src/web-auth/safari_view_controller.dart
- auth0_flutter_platform_interface/lib/src/web-auth/safariviewcontroller.dart
- auth0_flutter_platform_interface/lib/src/web-auth/web_auth_login_options.dart
- auth0_flutter_platform_interface/pubspec.lock
- auth0_flutter_platform_interface/test/method_channel_auth0_flutter_web_auth_test.dart
This PR adds support for [`SFSafariViewController`](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller) on iOS as an alternative to the default `ASWebAuthenticationSession`. Developers can optionally pass `presentationStyle` to control the behaviour.
Usage:
```dart
await webAuth.login(
safariViewController: const SafariViewController(
presentationStyle: SafariViewControllerPresentationStyle.formSheet));
```
Unit tests have been added, plus manual testing on an iOS simulator.
> af: [SDK-3958] Support SFSafariViewController

- auth0_flutter_platform_interface/pubspec.yaml
This corrects an issue from the [previous release PR](https://github.com/auth0/auth0-flutter/pull/200), and bump the version number.
> Release 1.1.0 (bump version)

- auth0_flutter/example/lib/example_app.dart
- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
- auth0_flutter/lib/src/web/credentials_extension.dart
- auth0_flutter/lib/src/web/js_interop.dart
- auth0_flutter/lib/src/web/jwt_decode.dart
- auth0_flutter/lib/src/web/jwt_decode_exception.dart
- auth0_flutter/lib/src/web/user_profile_extension.dart
- auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
This PR adds support for fetching the credentials, and for checking if there are any valid credentials stored. The following public methods were added:
- `credentials()` -> calls `getTokenSilently()` from the SPA SDK.
- `hasValidCredentials()` -> calls `isAuthenticated()` from the SPA SDK.
The changes were tested manually. Unit tests will be added in a future PR.
https://user-images.githubusercontent.com/5055789/221452162-4a7a8972-7c2e-4d9f-a109-776c204b4f9d.mov
> Add `credentials()` and `hasValidCredentials()` [SDK-3997]

- auth0_flutter/example/lib/example_app.dart
- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
- auth0_flutter/lib/src/web/auth0_flutter_web_platform_proxy.dart
- auth0_flutter/lib/src/web/js_interop.dart
- auth0_flutter/test/web/auth0_fluter_web_test.dart
- auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
- auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
- auth0_flutter_platform_interface/lib/src/web/popup_login_options.dart
This adds support for `loginWithPopup` in the client SDK.
Usage:
```dart
await auth0.loginWithPopup(
audience: 'http://my.api',
organizationId: 'org123',
invitationUrl: 'http://invitation.url',
scopes: {'openid'},
maxAge: 20,
popupWindow: window,
timeoutInSeconds: 120);
```
> [SDK-4002] Add support for loginWithPopup

- auth0_flutter/README.md
This PR documents the `loginWithPopup()` method in the README of the app-facing library, inside an expandable.
> Document `loginWithPopup()` on the README of  app-facing library [SDK-4106]

- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/lib/src/web/extensions/web_exception_extensions.dart
- auth0_flutter/test/web/auth0_flutter_web_test.dart
- auth0_flutter/test/web/extensions/web_exception_extension_test.dart
- auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
- auth0_flutter_platform_interface/lib/src/web/web_exception.dart
This PR wraps incoming exceptions from the underlying SPA client to a `WebException` type that surfaces the `error` and `error_description` properties.
> [SDK-4046] WebException wrapper

- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
- auth0_flutter/lib/src/web/extensions/credentials_options_extension.dart
- auth0_flutter/lib/src/web/js_interop.dart
- auth0_flutter/lib/src/web/js_interop_utils.dart
- auth0_flutter/test/web/auth0_flutter_web_test.dart
- auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
- auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
- auth0_flutter_platform_interface/lib/src/web/cache_mode.dart
- auth0_flutter_platform_interface/lib/src/web/credentials_options.dart
This PR adds support for the options to `getTokenSilently` in the underlying SDK, with the exception of `redirect_uri` (Ionic has a specific use case/need for this that doesn't apply here).
Covered with unit tests, also tested manually.
> [SDK-4110] Support options to `getTokenSilently`

- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter_platform_interface/lib/src/credentials.dart
- auth0_flutter_platform_interface/lib/src/web/cache_location.dart
- auth0_flutter_platform_interface/lib/src/web/client_options.dart
The `Credentials.refreshToken` property will always be `null` on the web platform because the refresh token is handled internally by the SPA SDK, and it's never exposed. This PR adds a note to the API documentation of `Credentials.refreshToken` about this.
> Add note to `Credentials.refreshToken` [SDK-4116]

- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter/lib/src/web/extensions/logout_options.extension.dart
- auth0_flutter/lib/src/web/js_interop.dart
The `LogoutOptions` type is only used internally, and shouldn't be exported from the app-facing package. It seems to have been mistakenly exported so it could be imported in `logout_options.extension.dart`, instead of importing it directly from the `auth0_flutter_platform_interface` package.
Also, this PR removes the unused `dart:html` import from `js_interop.dart`.
> Unexport `LogoutOptions`

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensions.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensionsTest.kt
This PR realigns the test for `AuthenticationException.isTooManyAttempts`. At the time the Flutter SDK was written, this exception type was not exposed by the underlying SDK. This support was added in [this PR](https://github.com/auth0/Auth0.Android/pull/615), so now the test can be updated to align with the others and be made to pass.
> [SDK-4121] fix: android unit test for isTooManyAttempts

- auth0_flutter/lib/auth0_flutter_web.dart
This PR clarifies the usage of `redirectUrl` and `returnToUrl` for `loginWithRedirect` and `logout` respectively; the are optional parameters but the user would normally want to set them explicitly.
> docs: clarify usage of redirectUrl and returnToUrl in docs

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensions.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensionsTest.kt
This PR brings into the `main` branch the fix for the Android unit tests introduced by https://github.com/auth0/auth0-flutter/pull/240 into the `beta` branch.
From the original PR:
> This PR realigns the test for `AuthenticationException.isTooManyAttempts`. At the time the Flutter SDK was written, this exception type was not exposed by the underlying SDK. This support was added in [this PR](https://github.com/auth0/Auth0.Android/pull/615), so now the test can be updated to align with the others and be made to pass.
> Fix android unit tests on `main`

- auth0_flutter/README.md
- auth0_flutter/example/README.md
This PR documents in the READMEs of `auth0_flutter` and its example app how to pass the port `3000` to `flutter run` when running a web app. This is the port number used in the callback URLs on the READMEs.
> Document how to pass the port `3000` when running a web app

- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/lib/src/web/js_interop_utils.dart
This PR inlines the usage of `AuthParamsExtension.prepare` and removed, as it was causing issues with the web build when using `flutter build web`. The compiler appeared to be aggressively optimising out any code that appeared after this extension call, causing login to not even be called. I have as yet to fully understand why (especially as calls to the other method `toGetTokenSilentlyOptions` work fine), however the change presented here fixes the issue for the meantime.
Fixes #256 
The changes don't affect the existing tests, and no new tests were added.
> fix: inline AuthParamsExtension.prepare usage and remove [SDK-4222]

- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/lib/src/web/js_interop_utils.dart
Similar to #260, this inlines the other extension method on a `@JS` type as it was exhibiting some weird behaviour that broke `loginWithPopup`. The extension class is also removed as no longer needed.
Resolves [an issue with loginWithPopup](https://github.com/auth0/auth0-flutter/issues/256#issuecomment-1561248472) reported in #256.
> af: inline usage of toGetTokenSilently options and remove extension

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginWithOtpApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/RenewApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/GetCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LoginWebAuthRequestHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/LoginWebAuthRequestHandlerTest.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandlerTest.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginWithOtpApiRequestHandlerTest.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/api/RenewApiRequestHandlerTest.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/GetCredentialsRequestHandlerTest.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandlerTest.kt
- auth0_flutter_platform_interface/pubspec.lock
- auth0_flutter_platform_interface/pubspec.yaml
- auth0_flutter_platform_interface/test/credentials_test.dart
Offering as an alternative to https://github.com/auth0/auth0-flutter/pull/206.
This aligns how Android and iOS parse dates. iOS is already formatting dates to `ISO8601String` by directly taking the `expiresAt` property, without modification. Android on the other hand is modifying this `expiresAt` by allowing it to be localised to whatever the systems `getDefaultLocale` is. 
To solve the issues we have seen with `ar` this ensures that all dates are using a consistent Locale of `Locale.US`. The test added `credentials_test` ~~is used just to illustrate the breaking change~~ is used to illustrate the issue with Arabic vs US English, but is actually fixed at the native level.
No references.
Put your device into `Arabic` and attempt to use this library to log in. You'll notice that it works in …
> Use Locale.US for Android

- auth0_flutter/CHANGELOG.md
- auth0_flutter/ios/auth0_flutter.podspec
- auth0_flutter/lib/src/version.dart
- auth0_flutter/pubspec.lock
- auth0_flutter/pubspec.yaml
**Changed**
- Document how to load the SPA SDK in index.html [\#254](https://github.com/auth0/auth0-flutter/pull/254) ([Widcket](https://github.com/Widcket))
- Document how to pass the port `3000` when running a web app [\#249](https://github.com/auth0/auth0-flutter/pull/249) ([Widcket](https://github.com/Widcket))
**Fixed**
- fix: inline AuthParamsExtension.prepare usage and remove [SDK-4222] [\#260](https://github.com/auth0/auth0-flutter/pull/260) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Use Locale.US for Android [\#238](https://github.com/auth0/auth0-flutter/pull/238) ([Mecharyry](https://github.com/Mecharyry))
[SDK-4222]: https://auth0team.atlassian.net/browse/SDK-4222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> af: release v1.2.0-beta.1

- auth0_flutter/example/lib/example_app.dart
This PR updates the example app to only call `setState()` after logout on the mobile platforms. On the web platform `onLoad()` will run after the redirect and set the state, making this unnecessary.
The changes were tested manually.
> Do not call `setState()` after web logout on the example app

- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter/lib/src/web/extensions/client_options_extensions.dart
- auth0_flutter/lib/src/web/js_interop.dart
- auth0_flutter_platform_interface/lib/src/web/client_options.dart
This PR adds the ability to specify `audience` and `scopes` to `onLoad()`. This fixes an issue in a specific scenario when using both `useRefreshTokens` and `cacheLocation: CacheLocation.localStorage` and logging in with `audience` causes the refresh token to be missing during initialization.
This happens because `audience` (and `scopes`) are used as part of the cache key when looking up the refresh token internally but until now a developer had no way to specify those values.
Fixes #271 
Tested manually by supplying `audience` and `scope` to `onLoad()`, logging in, and observing data coming through local storage and to `/authorize`.
> fix: allow audience and scope to be supplied during initialization

- auth0_flutter/CHANGELOG.md
- auth0_flutter/ios/auth0_flutter.podspec
- auth0_flutter/lib/src/version.dart
- auth0_flutter/pubspec.lock
- auth0_flutter/pubspec.yaml
**Fixed**
- fix: allow audience and scope to be supplied during initialization [\#272](https://github.com/auth0/auth0-flutter/pull/272) ([stevehobbsdev](https://github.com/stevehobbsdev))
> af: release v1.2.1

- auth0_flutter/ios/auth0_flutter.podspec
This PR pins Auth0.swift to **v2.3.2**, JWTDecode.swift to **v3.0.1**, and SimpleKeychain to **v1.0.1**, which is the last version that supports iOS 12.
Otherwise, Cocoapods will automatically pull the latest version of all these libraries.
> af: Pin Auth0.swift and its dependencies to last version that supports iOS 12

- .github/workflows/publish-af.yml
- .github/workflows/publish-afpi.yml
This PR adds GitHub Actions workflows for automating the publishing of `auth0_flutter` and `auth0_flutter_platform_interface`, by pushing tags formatted as `af-v{{version}}` and `afpi-v{{version}}`, respectively.
[Protected tags](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules) have been set up in the repo settings matching these patterns:
> Add automated publishing workflows [SDK-4044]

- .circleci/config.yml
This PR updates the CircleCI config to use the M1 resource class, as the macOS `medium` executor is being deprecated: https://discuss.circleci.com/t/macos-resource-deprecation-update/46891
The Xcode, iOS simulator and its iOS version were bumped as well.
> Use M1 resource class for iOS CI tests

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/Auth0FlutterPlugin.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/CredentialsManagerMethodCallHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/Auth0FlutterPluginTest.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/CredentialsManagerMethodCallHandlerTest.kt
We are using `applicationContext` to fetch the credentials instead of `Activity` which is not required and could cause issues when credentials are fetched from outside an activity
https://github.com/auth0/auth0-flutter/issues/233
We have updated the existing Unit Tests and added check that proper context is set.
> af: Use Application Context for Credentials Manager

- .semgrepignore
This PR adds a `.semgrepignore` manifest file and excludes directories that are (or potentially could) incorrectly trigger false positives.
> chore: Add `.semgrepignore` exclusions

- .github/workflows/pr-title-checker.yml
This PR pins the `pr-title-checker` third-party action to a full-length commit SHA — that of release 1.4.0.
Pinning an action to a full-length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository. https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
> chore(security): Pin `pr-title-checker` to commit SHA

- auth0_flutter/README.md
Recently there have been some changes in Manage, and now the **Token Endpoint Authentication Method** setting no longer shows up for mobile apps (because for this kind of app it must be `None`). Whereas for regular web apps and SPAs it's been moved to another tab:
Since it was possible (before this change) to set it to an invalid value for mobile apps, we had to point this out in the README of the app-facing package. Now that this setting is no longer available for mobile apps and was moved for SPAs, this PR reworks the respective documentation.
> Update PKCE-related documentation

- auth0_flutter/README.md
Surfacing an important step when setting up Android apps to support `https` schemes.
Aligning the Pub.dev docs with the same level of convenience as guidance found in other Auth0 documentation surrounding the use of `https` schemes:
- https://auth0.com/docs/quickstart/native/flutter/interactive#configure-android
- https://auth0.com/blog/get-started-with-flutter-authentication/#Configure-the-SDK
Docs-only change, should not affect tests.
> Add Android App Links guidance to https schemes

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.lock
- auth0_flutter_platform_interface/pubspec.yaml
**Changed**
- Lock Auth0.Android version to avoid dynamic versioning [\#311](https://github.com/auth0/auth0-flutter/pull/311) ([poovamraj](https://github.com/poovamraj))
- Add namespace to build.gradle [\#290](https://github.com/auth0/auth0-flutter/pull/290) ([poovamraj](https://github.com/poovamraj))
**Fixed**
- Fix access token expiry android [\#315](https://github.com/auth0/auth0-flutter/pull/315) ([poovamraj](https://github.com/poovamraj))
> afpi: release afpi-v1.3.0

- auth0_flutter/CHANGELOG.md
- auth0_flutter/ios/auth0_flutter.podspec
- auth0_flutter/lib/src/version.dart
- auth0_flutter/pubspec.yaml
**Changed**
- Lock Auth0.Android version to avoid dynamic versioning [\#311](https://github.com/auth0/auth0-flutter/pull/311) ([poovamraj](https://github.com/poovamraj))
- Add namespace to build.gradle [\#290](https://github.com/auth0/auth0-flutter/pull/290) ([poovamraj](https://github.com/poovamraj))
- af: Pin Auth0.swift and its dependencies to last version that supports iOS 12 [\#276](https://github.com/auth0/auth0-flutter/pull/276) ([Widcket](https://github.com/Widcket))
**Fixed**
- Fix access token expiry android [\#315](https://github.com/auth0/auth0-flutter/pull/315) ([poovamraj](https://github.com/poovamraj))
- af: Use Application Context for Credentials Manager [\#289](https://github.com/auth0/auth0-flutter/pull/289) ([poovamraj](https://github.com/poovamraj))
> af: Release af-v1.3.0

- auth0_flutter_platform_interface/lib/src/credentials.dart
- auth0_flutter_platform_interface/test/credentials_test.dart
- auth0_flutter_platform_interface/test/method_channel_auth0_flutter_auth_test.dart
- auth0_flutter_platform_interface/test/method_channel_auth0_flutter_web_auth_test.dart
- auth0_flutter_platform_interface/test/method_channel_credentials_manager_test.dart
Currently, both native implementations (iOS and Android) provide credentials to the Dart layer that include an `expiresAt` value formatted as ISO 8601 date with UTC time zone. More specifically, the format used follows the [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339)'s profile of ISO 8601 dates, which is somewhat more restrictive for the sake of simplicity:
Among the fields that the RFC 3339 deems mandatory (that ISO 8601 does not) is the time zone. So, a RFC 3339 date must contain time zone information to be valid. The native implementations, in particular, use UTC as the time zone.
Besides passing RFC 3339 `expiresAt` dates *to* the Dart layer, the native implementations expect that any `expiresAt` dates received *from* the Dart layer also to be RFC 3339 dates. But, here comes the …
> afpi: Ensure Dart `expiresAt` uses the UTC time zone

- auth0_flutter/example/android/app/build.gradle
- auth0_flutter/example/android/app/src/main/AndroidManifest.xml
This PR fixes a couple of errors preventing the build of the Android example app on Mac M2 processors.
> Fix build of Android example app on Mac ARM

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Fixed**
- afpi: Ensure Dart `expiresAt` uses the UTC time zone [\#331](https://github.com/auth0/auth0-flutter/pull/331) ([Widcket](https://github.com/Widcket))
> Release afpi-v1.3.1

- .github/actions/setup-publish/action.yml
- .github/workflows/publish-af.yml
- .github/workflows/publish-afpi.yml
This PR fixes the CI publish workflow, as it was failing because the [dart-lang/setup-dart/.github/workflows/publish.yml@v1](https://github.com/dart-lang/setup-dart/blob/main/.github/workflows/publish.yml) action installs dependencies using `dart pub get`, but our packages depend on Flutter, and as such need to use `flutter pub get` instead:
But still the Dart SDK needs to be installed using that action, as it contains [the logic](https://github.com/dart-lang/setup-dart/blob/main/lib/main.dart#L169) necessary for getting the token used for publishing.
Unlike that action, we're not adding a dry run step because it [returns a non-zero error code](https://github.com/dart-lang/pub/issues/3807#issuecomment-1602176761) (that fails the workflow) when there are warnings, and the `auth0_flutter` …
> Fix publish workflow

- auth0_flutter_platform_interface/lib/src/auth/auth_multifactor_challenge_options.dart
This PR updates the import order in `auth0_flutter_platform_interface/lib/src/auth/auth_multifactor_challenge_options.dart`, as the respective analyze rule changed on Flutter 3.16, and now `flutter analyze` fails.
That is causing the CI to fail in all the other (currently) open PRs.
> afpi: Fix import order for Flutter 3.16

- auth0_flutter/example/ios/UITests/SmokeTests.swift
Currently, the iOS smoke tests have a timeout of 10 seconds when waiting for UI elements to appear. Looking at recent failures, this value does not seem to be enough, as the UL page hasn't finished rendering by the time this timeout expires:
This PR raises the timeout to 30m seconds to give the UL page enough time to finish rendering.
> Increase the timout of iOS smoke tests

- auth0_flutter/EXAMPLES.md
- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter/lib/src/web/extensions/client_options_extensions.dart
- auth0_flutter_platform_interface/lib/src/web/client_options.dart
Adds support for passing custom parameters to onLoad, which are used as global custom parameters in the underlying Auth0-SPA-JS SDK.
Closes #345
Update the sample application [here](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/example/lib/example_app.dart#L37):
```
auth0Web.onLoad(parameters: {'foo': 'bar'}).then((final credentials) => setState(() {
_output = credentials?.idToken ?? '';
_isLoggedIn = credentials != null;
}));
```
> Add support for passing parameters onLoad

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Added**
- Add support for passing parameters onLoad [\#363](https://github.com/auth0/auth0-flutter/pull/363) ([frederikprijck](https://github.com/frederikprijck))
**Changed**
- Remove and gitignore `pubspec.lock` files [\#340](https://github.com/auth0/auth0-flutter/pull/340) ([Widcket](https://github.com/Widcket))
> Release afpi-v1.4.0

- auth0_flutter/android/build.gradle
This PR makes sure the Kover Gradle plugin is properly installed on the library's Gradle config. Previously, it was installed on the example app's config and *applied* on the library's config. When installed on another app, it couldn't find the plugin.
Fixes https://github.com/auth0/auth0-flutter/issues/369
This was tested manually on the Quickstart sample app.
> af: Install Kover from the library's Gradle config

- .github/workflows/main.yml
This PR updates the iOS smoke test job to use Xcode 15.0.1.
> Use Xcode 15 to run iOS smoke tests

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Added**
- Add support for macOS [\#381](https://github.com/auth0/auth0-flutter/pull/381) ([Widcket](https://github.com/Widcket))
> Release afpi-v1.5.0

- DEVELOPMENT.md
- README.md
- auth0_flutter/EXAMPLES.md
- auth0_flutter/FAQ.md
- auth0_flutter/README.md
- auth0_flutter_platform_interface/README.md
This PR documents the recently introduced HTTPS redirect URLs feature: https://github.com/auth0/auth0-flutter/pull/417
> Document the HTTPS redirect URLs feature [SDK-4755]

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Added**
- Add support for HTTPS redirect URLs [SDK-4754] [\#417](https://github.com/auth0/auth0-flutter/pull/417) ([Widcket](https://github.com/Widcket))
[SDK-4754]: https://auth0team.atlassian.net/browse/SDK-4754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> afpi: Release afpi-v1.6.0

- auth0_flutter/darwin/auth0_flutter.podspec
- auth0_flutter/ios/auth0_flutter.podspec
- auth0_flutter/macos/auth0_flutter.podspec
Bumped the Auth0 Dependency on the Podspec to 2.7.0, which includes Privacy Manifests
https://github.com/auth0/Auth0.swift/pull/841
https://github.com/auth0/Auth0.swift/pull/842
See more on: https://developer.apple.com/news/?id=3d8a9yyh
See more on: https://developer.apple.com/support/third-party-SDK-requirements/
> iOS - Bump Auth0 dependency version

- auth0_flutter/CHANGELOG.md
- auth0_flutter/darwin/auth0_flutter.podspec
- auth0_flutter/ios/auth0_flutter.podspec
- auth0_flutter/lib/src/version.dart
- auth0_flutter/macos/auth0_flutter.podspec
- auth0_flutter/pubspec.yaml
**Added**
- iOS - Bump Auth0 dependency version [\#435](https://github.com/auth0/auth0-flutter/pull/435) ([martin-headspace](https://github.com/martin-headspace))
> Release af-v1.7.0

- auth0_flutter/darwin/auth0_flutter.podspec
- auth0_flutter/ios/auth0_flutter.podspec
- auth0_flutter/macos/auth0_flutter.podspec
Upgraded dependency on Auth0.swift to 2.7.1 to fix the declaration of privacy manifest
https://github.com/auth0/Auth0.swift/issues/845
Tried building the sample app using the version `2.7.1` of `Auth0.swift` by linking the pod as a static library, static & dynamic framework and it was **successful** in all the cases, where as building with version `2.7.0` when linking `Auth0.swift` as either a static library/framework resulted in an error message saying `Multiple commands produce PrivacyInfo.xcprivacy` as shown below:
> (af) chore: upgraded dependency on Auth0.swift to 2.7.1 to fix the declaration of privacy manifest

- auth0_flutter/CHANGELOG.md
- auth0_flutter/darwin/auth0_flutter.podspec
- auth0_flutter/ios/auth0_flutter.podspec
- auth0_flutter/lib/src/version.dart
- auth0_flutter/macos/auth0_flutter.podspec
- auth0_flutter/pubspec.yaml
**Fixed**
- (af) chore: upgraded dependency on Auth0.swift to 2.7.1 to fix the declaration of privacy manifest [\#448](https://github.com/auth0/auth0-flutter/pull/448) ([desusai7](https://github.com/desusai7))
> Release af-v1.7.1

- .github/workflows/pr-title-checker.yml
Replace `pull_request_target ` with `pull_request ` in the github workflow
> Replaced pull_request_target with pull_request to fix the workflow security issue

- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginWithOtpApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/RenewApiRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/GetCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/credentials_manager/SaveCredentialsRequestHandler.kt
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LoginWebAuthRequestHandler.kt
- auth0_flutter_platform_interface/lib/src/credentials.dart
After spending quite some time trying to understand why our access tokens would not be refreshed, I realized that something was wrong with the `expiresAt` field. The issue affects (at least) Android because the UTC timezone is added in the format while the formatter itself is timezone-unaware.
With the following added print statements, you can observe that the `Credentials.expiresAt` is formatted from local time with an appended Z, which means we lose the timezone information.
```
I/System.out(18918): RenewApiRequestHandler::onSuccess credentials.expiresAt Tue Jul 23 08:49:05 GMT+02:00 2024
I/System.out(18918): RenewApiRequestHandler::onSuccess formattedDate 2024-07-23T08:49:05.555Z
```
Making sure all `SimpleDateFormat` are set to the UTC timezone fixes the issue, but since …
> Use java.time.Instant instead of java.text.SimpleDateFormat

- .github/actions/rl-scanner/action.yml
- .github/workflows/main.yml
- .github/workflows/publish-af.yml
- .github/workflows/publish-afpi.yml
- .github/workflows/rl-scanner.yml
Integrating Reversing Labs Scanner to add an extra layer of protection from threats
[Reversing Labs Integration Documentation](https://www.reversinglabs.com/integrations)
> Adding ReversingLabs workflow

- .github/actions/smoke-tests-darwin/action.yml
- .github/actions/unit-tests-darwin/action.yml
- .github/workflows/main.yml
This PR pins all usages of `actions/upload-artifact` to v4. This is necessary because Dependabot does not seem to be able to bump the version of `actions/upload-artifact` used inside composite actions, leading to a version mismatch between:
- Workflows using `actions/upload-artifact` directly
- Workflows using `actions/upload-artifact` indirectly, through a composite action
> Use actions/upload-artifact@v4 on CI workflows

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Added**
- feat: Added support for passwordless authentication [\#503](https://github.com/auth0/auth0-flutter/pull/503) ([pmathew92](https://github.com/pmathew92))
**Changed**
- Updated the android gradle version [\#490](https://github.com/auth0/auth0-flutter/pull/490) ([pmathew92](https://github.com/pmathew92))
- Update Swift dependencies [\#493](https://github.com/auth0/auth0-flutter/pull/493) ([Widcket](https://github.com/Widcket))
- Minor readme update [\#483](https://github.com/auth0/auth0-flutter/pull/483) ([pmathew92](https://github.com/pmathew92))
- Set `compileSdk` to `34` to match Auth0.Android [\#494](https://github.com/auth0/auth0-flutter/pull/494) ([Widcket](https://github.com/Widcket))
- Use java.time.Instant instead of java.text.SimpleDateFormat …
> Release afpi-v1.8.0

- .github/workflows/main.yml
This PR updates the CI config to make sure that running `flutter analyze` does not fail the CI on warnings and infos.
https://github.com/flutter/flutter/issues/31918
> Make sure `flutter analyze` warnings and infos don't fail CI

- auth0_flutter/lib/src/web/extensions/user_profile_extension.dart
- auth0_flutter/test/web/extensions/user_profile_extension_test.dart
This PR makes sure to check if the `locale` value in the user profile is a string value. If it's not, then it sets `locale` to `null`.
This is necessary when some third-party OIDC connection doesn't return the locale as specified in the OIDC spec (e.g. LinkedIn), to keep the login from failing:
Also, the handling of the `phone_verified` claim was updated to match that of `email_verified`.
Fixes https://github.com/auth0/auth0-flutter/issues/432
Unit tests were added. The change was also tested manually by logging in using a LinkedIn connection.
> af: Ignore locale when it's not a string

- .github/actions/setup-darwin/action.yml
- .github/workflows/main.yml
This PR pins the version of Ruby to be used by GitHub Actions to **v3.3.1** to fix a CI issue:
Also, the `setup-ruby` action was updated to **v1.221.0**.
> Use Ruby 3.3.1 on Github Actions

- auth0_flutter/README.md
This PR adds the following paragraph to the auth0_swift README:
> Whenever possible, Auth0 recommends using Universal Links as a secure way to link directly to content within your iOS app. Custom URL schemes can be subject to [client impersonation attacks](https://datatracker.ietf.org/doc/html/rfc8252#section-8.6).
> Add Universal Links recommendation to the README

- auth0_flutter/example/lib/example_app.dart
- auth0_flutter/example/pubspec.yaml
- auth0_flutter/example/web/index.html
- auth0_flutter/lib/src/web.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/lib/src/web/auth0_flutter_web_platform_proxy.dart
- auth0_flutter/lib/src/web/extensions/credentials_extension.dart
- auth0_flutter/lib/src/web/extensions/credentials_options_extension.dart
- auth0_flutter/lib/src/web/extensions/web_exception_extensions.dart
- auth0_flutter/lib/src/web/js_interop.dart
- auth0_flutter/lib/src/web/js_interop_utils.dart
- auth0_flutter/pubspec.yaml
- auth0_flutter/test/web/auth0_extension_type_mocks.dart
- auth0_flutter/test/web/auth0_flutter_web_test.dart
- auth0_flutter/test/web/auth0_flutter_web_test.mocks.dart
- auth0_flutter/test/web/extensions/credentials_extension_test.dart
- auth0_flutter/test/web/extensions/web_exception_extension_test.dart
- auth0_flutter_platform_interface/pubspec.yaml
This PR adds support for WASM compilation 
#463 
This has been tested by running the example app with the  following command
`flutter run -d chrome --web-port 3000 --wasm `
> Added support for WASM compilation

- auth0_flutter_platform_interface/lib/src/credentials.dart
- auth0_flutter_platform_interface/lib/src/user_profile.dart
- auth0_flutter_platform_interface/test/credentials_test.dart
- auth0_flutter_platform_interface/test/method_channel_credentials_manager_test.dart
- auth0_flutter_platform_interface/test/user_profile_test.dart
- Add userProfile to Credentials.toMap() method
- Implement toMap() method in UserProfile class
- Update existing tests and add new UserProfile tests
Added tests for the updated code and all of the tests pass
Actually messed up signing commits here https://github.com/auth0/auth0-flutter/pull/475 🙈
So created a new one
> feat(auth): 🔐 Add UserProfile serialization and include in Credentials

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Added**
- implement app state getter for web [\#509](https://github.com/auth0/auth0-flutter/pull/509) ([navaronbracke](https://github.com/navaronbracke))
- feat(auth): 🔐 Add UserProfile serialization and include in Credentials [\#556](https://github.com/auth0/auth0-flutter/pull/556) ([Rohithgilla12](https://github.com/Rohithgilla12))
**Fixed**
- Fixed the WASM compilation issue on 3.24 version of flutter [\#547](https://github.com/auth0/auth0-flutter/pull/547) ([pmathew92](https://github.com/pmathew92))
> Release afpi-v1.10.0

- .github/actions/setup-android/action.yml
- auth0_flutter/EXAMPLES.md
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/CredentialsManagerMethodCallHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/CredentialsManagerMethodCallHandlerTest.kt
- auth0_flutter/darwin/Classes/CredentialsManager/CredentialsManagerHandler.swift
- auth0_flutter/example/android/app/src/main/res/values/strings.xml.example
- auth0_flutter/example/ios/Tests/CredentialsManager/CredentialsManagerHandlerTests.swift
- auth0_flutter/lib/auth0_flutter.dart
- auth0_flutter/lib/src/mobile/credentials_manager.dart
- auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
- auth0_flutter_platform_interface/lib/src/credentials-manager/credentials_manager_configuration.dart
- auth0_flutter_platform_interface/lib/src/request/request.dart
- auth0_flutter_platform_interface/test/method_channel_credentials_manager_test.dart
This PR adds support to configure the CredentialsManager class on both Android and iOS platforms. This change allows user to set the `sharedpreferenceName` in Android and `secretKey` , `accessGroup` and `accessibility` on iOS while setting up the CredentialsManager in `auth0_flutter`
#553
> Added support to configure credentials manager for iOS and Android 

- auth0_flutter_platform_interface/lib/src/credentials-manager/credentials_manager_exception.dart
- auth0_flutter_platform_interface/lib/src/web-auth/web_authentication_exception.dart
This PR adds new properties in the `web_authentication_exception` and `credentials_manager_exception` class to easily compare for specific error scenarios
#395
> chore : added new properties to web_authentication_exception and credentials_manager_exception class

- .github/workflows/main.yml
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/web_auth/LoginWebAuthRequestHandler.kt
- auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/LoginWebAuthRequestHandlerTest.kt
- auth0_flutter/example/lib/example_app.dart
- auth0_flutter/lib/src/mobile/web_authentication.dart
- auth0_flutter_platform_interface/lib/src/web-auth/web_auth_login_options.dart
- auth0_flutter_platform_interface/test/web_auth_login_options_test.dart
In android we have api to input allowed browser packages for web auth login. this is required particularly to provide a list of browsers that are allowed to open the universal login url
This api is exposed already in android. Its exposed in flutter for addressing https://github.com/auth0/auth0-flutter/issues/392
Reviewers can pass allowedPackages while performing login via web auth.
When the user's default browser is in the allowlist, it uses the default browser
When the user's default browser is not in the allowlist, but the user has another allowed browser installed, the allowed browser is used instead
When the user's default browser is not in the allowlist, and the user has no other allowed browser installed, an error is returned
> dart api to input allowed browser packages for web auth login

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Added**
- chore: added new renewCredentials method to fetch a new set of credentials [\#610](https://github.com/auth0/auth0-flutter/pull/610) ([pmathew92](https://github.com/pmathew92))
- dart api to input allowed browser packages for web auth login [\#611](https://github.com/auth0/auth0-flutter/pull/611) ([NandanPrabhu](https://github.com/NandanPrabhu))
- chore : added new properties to web_authentication_exception and credentials_manager_exception class [\#609](https://github.com/auth0/auth0-flutter/pull/609) ([pmathew92](https://github.com/pmathew92))
- Added webAuth cancel for ios to prevent active transaction errors [\#573](https://github.com/auth0/auth0-flutter/pull/573) ([pmathew92](https://github.com/pmathew92))
> Release afpi-v1.12.0

- auth0_flutter/lib/auth0_flutter_web.dart
- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- [ X] All new/changed/fixed functionality is covered by tests (or N/A)
- [ X] I have added documentation for all new/changed functionality (or N/A)
Added redirectUrl and cacheLocation to the Auth0Web constructor: These optional parameters allow developers to configure the redirect URI and authentication state storage location once at initialization. This ensures consistency between loginWithRedirect and onLoad() calls.
Fixed onLoad() silent authentication: Previously, onLoad() could fail on page refresh due to a redirect_uri mismatch or a missing_transaction error.
https://github.com/auth0/auth0-flutter/issues/409
The new functionality is covered by manual end-to-end testing.
> Adding fix for OnLoad() for refresh redirecting

- .github/actions/rl-scanner/action.yml
- .github/actions/setup-darwin/action.yml
- .github/workflows/check-symlinks.yml
- .github/workflows/main.yml
- .github/workflows/publish-af.yml
- .github/workflows/publish-afpi.yml
- .github/workflows/rl-scanner.yml
- auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginWithSMSCodeApiRequestHandler.kt
- Fixed `LoginWithSMSCodeApiRequestHandler` to pass the correct phoneNumber argument to `AuthenticationAPIClient.loginWithPhoneNumber()` instead of email.
- This ensures that SMS-based authentication works correctly without causing `null cannot be cast to non-null type kotlin.String errors`.
- Fixes #632
Manual verification steps:
- Run the included example app.
- Use the passwordless embedded flow:
Start authentication with:
```
api.startPasswordlessWithPhoneNumber(phoneNumber: "+XXXXXXX")
```
- Then log in with:
```
api.loginWithSmsCode(
phoneNumber: "+XXXXXXX",
verificationCode: "123456"
)
```
No crash or null cannot be cast error occurs.
> fix(android): SMS login to use phoneNumber instead of email

- auth0_flutter/example/web/index.html
- auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
- auth0_flutter/test/web/auth0_flutter_web_test.dart
- [X ] All new/changed/fixed functionality is covered by tests (or N/A)
- [ X] I have added documentation for all new/changed functionality (or N/A)
Resolves the inconsistency where the web platform required an invitation ticket ID for the `invitationUrl` parameter, while mobile platforms required the full URL.
This change introduces a helper function that checks if the provided `invitationUrl` is a full URL. If it is, it parses the `invitation` query parameter to extract the ticket ID. If it's not a full URL, it's assumed to be the ticket ID itself.
This makes the `invitationUrl` parameter behave consistently across all platforms, allowing developers to pass the full invitation URL without causing an "invitation not found" error on the web. …
> Resolves the inconsistency where the web platform required an invitation ticket ID for the  parameter, while mobile platforms required the full URL.

- auth0_flutter_platform_interface/CHANGELOG.md
- auth0_flutter_platform_interface/pubspec.yaml
**Fixed**
- Resolves the inconsistency where the web platform required an invitation ticket ID for the  parameter, while mobile platforms required the full URL. [\#645](https://github.com/auth0/auth0-flutter/pull/645) ([utkrishtsahu](https://github.com/utkrishtsahu))
- fix(android): SMS login to use phoneNumber instead of email [\#633](https://github.com/auth0/auth0-flutter/pull/633) ([hiiiP0wer](https://github.com/hiiiP0wer))
- Adding fix for OnLoad() for refresh redirecting [\#624](https://github.com/auth0/auth0-flutter/pull/624) ([utkrishtsahu](https://github.com/utkrishtsahu))
> Release afpi-v1.13.0
