auth0/auth0-flutter

auth0_flutter/analysis_options.yaml
auth0_flutter/example/lib/main.dart
auth0_flutter/example/pubspec.yaml
auth0_flutter/lib/src/authentication_api.dart
auth0_flutter/pubspec.yaml
auth0_flutter_platform_interface/analysis_options.yaml
auth0_flutter_platform_interface/lib/src/web-auth/id_token_validation_config.dart
auth0_flutter_platform_interface/pubspec.yaml
auth0_flutter_platform_interface/test/method_channel_auth0_flutter_auth_test.dart
auth0_flutter_platform_interface/test/method_channel_credentials_manager_test.dart

This PR upgrades the `flutter_lints` library to v2 in all packages, and fixes the issues flagged by `flutter analyze`. Also, the rule `package_api_docs` was enabled.

Update `flutter_lints` to v2

---

.github/ISSUE_TEMPLATE/config.yml
README.md
auth0_flutter/README.md
auth0_flutter_platform_interface/README.md

This PR updates the following READMEs for the upcoming FA release:
- Root README
- auth0_flutter README
- auth0_flutter_platform_interface README
References to "Beta" were replaced with "First Availability", and the badges were updated. Also, in the case of the auth0_flutter README, the code snippets were updated to reflect the current public API and documentation about the Credentials Manager was added.

Update READMEs for FA [SDK-3495]

---

auth0_flutter/FAQ.md
auth0_flutter/README.md

This PR updates the SDK README and FAQ according to the current state of the API.

Update SDK README and FAQ with latest API changes [SDK-3505]

---

auth0_flutter/pubspec.lock
auth0_flutter_platform_interface/CHANGELOG.md
auth0_flutter_platform_interface/pubspec.yaml

This is a [First Availability](https://auth0.com/docs/troubleshoot/product-lifecycle/product-release-stages#first-availability) release of the **Auth0 Flutter SDK**! 🎉 
This release includes the addition of a Credentials Manager: a mechanism to manage the tokens returned from Auth0, including the ability to automatically renew the access token when expired (web authentication only). [Read more about the credentials manager](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#credentials-manager) in the `auth0_flutter` package readme.

Release 1.0.0-fa.0 (auth0_flutter_platform_interface)

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.lock
auth0_flutter/pubspec.yaml

This is a [First Availability](https://auth0.com/docs/troubleshoot/product-lifecycle/product-release-stages#first-availability) release of the **Auth0 Flutter SDK**! 🎉 
This release includes the addition of a Credentials Manager: a mechanism to manage the tokens returned from Auth0, including the ability to automatically renew the access token when expired (web authentication only). [Read more about the credentials manager](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#credentials-manager) in the readme.

Release 1.0.0-fa.0 (auth0_flutter)

---

auth0_flutter_platform_interface/test/method_channel_credentials_manager_test.dart

This PR adds a missing unit test to the platform interface package.

Add missing platform interface test

---

auth0_flutter/pubspec.yaml
auth0_flutter_platform_interface/pubspec.yaml

Pub.dev docks points from packages whose description is shorter than 60 chars or longer than 180 chars. Both packages had it shorter. This PR updates the descriptions so they're at least 60 chars long.

Update package descriptions to comply with pub.dev

---

auth0_flutter/example/lib/example_app.dart
auth0_flutter/lib/src/credentials_manager.dart
auth0_flutter/test/authentication_api_test.dart
auth0_flutter/test/credentials_manager_test.dart
auth0_flutter_platform_interface/lib/src/auth/auth_reset_password_options.dart
auth0_flutter_platform_interface/lib/src/auth0_exception.dart
auth0_flutter_platform_interface/lib/src/credentials-manager/method_channel_credentials_manager.dart
auth0_flutter_platform_interface/lib/src/credentials-manager/options/get_credentials_options.dart
auth0_flutter_platform_interface/lib/src/database_user.dart
auth0_flutter_platform_interface/lib/src/method_channel_auth0_flutter_auth.dart
auth0_flutter_platform_interface/lib/src/request/request.dart
auth0_flutter_platform_interface/test/api_exception_test.dart
auth0_flutter_platform_interface/test/auth0_exception_test.dart
auth0_flutter_platform_interface/test/credential_manager_exception_test.dart
auth0_flutter_platform_interface/test/method_channel_auth0_flutter_auth_test.dart
auth0_flutter_platform_interface/test/method_channel_auth0_flutter_web_auth_test.dart

Pub.dev docks points from packages that have formatting issues. So `flutter format` was run for all packages. This PR incorporates the formatting changes made by `flutter format`.

Apply `flutter format` to comply with pub.dev

---

README.md
auth0_flutter/README.md
auth0_flutter_platform_interface/README.md

This PR updates all the READMEs for the upcoming GA release, and also incorporates some feedback to improve the Android setup instructions.

Update READMEs for GA [SDK-3514]

---

codecov.yml

This PR removes the `comment: false` line from the `codecov.yml` file, which disabled the Codecov PR comment.

Reenable Codecov comments

---

auth0_flutter/CHANGELOG.md
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.yaml

**Fixed**
- #162 ([widcket](https://github.com/widcket))

Release v1.0.1

---

README.md
auth0_flutter/README.md

- Headers should be removed (something I noticed when comparing other PRs)
- Also placed the banner on the root readme (originally was just on the `auth0_flutter` package)

[readme redesign] tweak headings and banners

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.yaml

**Changed**
- af: Replace usages of `getOrDefault()` [\#179](https://github.com/auth0/auth0-flutter/pull/179) ([Widcket](https://github.com/Widcket))
- af: Update Podspec [\#180](https://github.com/auth0/auth0-flutter/pull/180) ([Widcket](https://github.com/Widcket))
**Security**
- [Snyk] Security upgrade slather from 2.7.2 to 2.7.2 [\#176](https://github.com/auth0/auth0-flutter/pull/176) ([crew-security](https://github.com/crew-security))

Release v1.0.2

---

auth0_flutter/example/Gemfile.lock

This PR updates the example's `Gemfile.lock` to reflect latest dependency versions, and resolves Snyk warnings.

chore: Update Example Dependencies Lockfile

---

auth0_flutter_platform_interface/CHANGELOG.md

**Added**
- Added support for `loginWithOtp`  [\#172](https://github.com/auth0/auth0-flutter/pull/172) ([wferem1](https://github.com/wferem1))
- Added support for SafariViewController [\#198](https://github.com/auth0/auth0-flutter/pull/198) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- Upgrade Flutter used for build, and fix linter warnings [\#199](https://github.com/auth0/auth0-flutter/pull/199) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Fix README links [\#184](https://github.com/auth0/auth0-flutter/pull/184) ([Widcket](https://github.com/Widcket))

Release v1.1.0 (platform interface)

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.lock
auth0_flutter/pubspec.yaml

**Added**
- Support SFSafariViewController [\#198](https://github.com/auth0/auth0-flutter/pull/198) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- Fix Apple login connection crash in Android [\#195](https://github.com/auth0/auth0-flutter/pull/195) ([poovamraj](https://github.com/poovamraj))

Release 1.1.0

---

auth0_flutter/test/web/jwt_decode_test.dart
auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
auth0_flutter_platform_interface/lib/src/testing/auth0_exception_matcher.dart

This PR adds unit tests for the utility method `JWT.decode()`. Also a custom matcher was added to aid with exception testing.

Add JWT decoder tests

---

auth0_flutter/EXAMPLES.md

This PR updates EXAMPLES.md to include web snippets. Also the contents were reorganized to make it easier to tell at glance if a given feature is supported on mobile and web, or mobile only.

Update the EXAMPLES to include web content [SDK-4007]

---

auth0_flutter/test/web/auth0_fluter_web_test.dart

This PR adds unit tests for the JS interop of the `credentials()` and `hasValidCredentials()` methods.
Complements #208, #209, and #210.

Add unit tests for `credentials()` and `hasValidCredentials()` [SDK-4004]

---

auth0_flutter/lib/auth0_flutter_web.dart
auth0_flutter/lib/src/mobile/authentication_api.dart
auth0_flutter/lib/src/mobile/web_authentication.dart
auth0_flutter_platform_interface/lib/src/id_token_validation_config.dart
auth0_flutter_platform_interface/lib/src/web-auth/safari_view_controller.dart
auth0_flutter_platform_interface/lib/src/web/cache_location.dart
auth0_flutter_platform_interface/lib/src/web/client_options.dart

This PR does minor tweaks and improvements to the API docs of the web platform (and a few other API docs as well):
- Fixed typos
- Fixed minor formatting issues
- Minor readability adjustments

Improve API docs [SDK-4105]

---

README.md
auth0_flutter/EXAMPLES.md

This PR fills in the remaining snippets in EXAMPLES.md, that were empty and marked as 'TBC':
- Logout
- Custom properties
- Error handling
Note that this doesn't include docs for `loginWithPopup()`, which will be added to the README in a future PR.

Add missing snippets to EXAMPLES.md

---

auth0_flutter/lib/auth0_flutter.dart
auth0_flutter/lib/auth0_flutter_web.dart

This PR exports the `WebException` exception from the `auth0_flutter_platform_interface` package.

Export `WebException` [SDK-4115]

---

auth0_flutter/FAQ.md

This PR updates the FAQ to use the GitHub-supported admonitions ("Notes" and "Warning").

Update FAQ to use markdown admonitions

---

auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
auth0_flutter/test/web/auth0_flutter_web_test.dart
auth0_flutter/test/web/jwt_decode_test.dart
auth0_flutter/test/web/matchers/auth0_exception_matcher.dart
auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
auth0_flutter_platform_interface/pubspec.yaml

This PR fixes a few issues flagged by `flutter analyze`.

Fix `flutter analyze` issues

---

auth0_flutter_platform_interface/CHANGELOG.md
auth0_flutter_platform_interface/pubspec.yaml

This release adds support for the web platform.
**Added**
- [SDK-4110] Support options to `getTokenSilently` [\#232](https://github.com/auth0/auth0-flutter/pull/232) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4046] WebException wrapper [\#227](https://github.com/auth0/auth0-flutter/pull/227) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4009] Add support for custom parameters [\#226](https://github.com/auth0/auth0-flutter/pull/226) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4002] Add support for loginWithPopup [\#224](https://github.com/auth0/auth0-flutter/pull/224) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4001] Logout for web platform [\#223](https://github.com/auth0/auth0-flutter/pull/223) …

afpi: Release v1.2.0-beta.0

---

auth0_flutter/example/pubspec.yaml
auth0_flutter/pubspec.lock
auth0_flutter/pubspec.yaml

This PR bumps the version of `auth0_flutter_platform_interface` to [v1.2.0-beta.0](https://pub.dev/packages/auth0_flutter_platform_interface/versions/1.2.0-beta.0).

af: Bump `auth0_flutter_platform_interface` to beta version

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.yaml

This release adds support for the web platform.
**Added**
- [SDK-4110] Support options to `getTokenSilently` [\#232](https://github.com/auth0/auth0-flutter/pull/232) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4046] WebException wrapper [\#227](https://github.com/auth0/auth0-flutter/pull/227) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4009] Add support for custom parameters [\#226](https://github.com/auth0/auth0-flutter/pull/226) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4002] Add support for loginWithPopup [\#224](https://github.com/auth0/auth0-flutter/pull/224) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-4001] Logout for web platform [\#223](https://github.com/auth0/auth0-flutter/pull/223) …

af: Release v1.2.0-beta.0

---

auth0_flutter/README.md

This PR documents in the README of the app-facing package how to load the [SPA SDK](https://github.com/auth0/auth0-spa-js) by adding a `<script>` tag to the `index.html` file.

Document how to load the SPA SDK in index.html

---

auth0_flutter/EXAMPLES.md
auth0_flutter/README.md

PR includes a number of readme and documentation tweaks for the forthcoming web support:
- includes API ref for web
- rewords common tasks
- includes web-related details for `credentials` and `hasCredentials`

af: readme tweaks for web support [SDK-4217]

---

auth0_flutter_platform_interface/CHANGELOG.md
auth0_flutter_platform_interface/pubspec.yaml

This release adds official support for the Web platform! 🎉 Please checkout [the readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) for full usage instructions for all supported platforms:
Other changes in this release:
**Added**
- Add support for requesting MFA challenges [SDK-4052] [\#251](https://github.com/auth0/auth0-flutter/pull/251) ([Widcket](https://github.com/Widcket))
**Fixed**
- Use Locale.US for Android [\#238](https://github.com/auth0/auth0-flutter/pull/238) ([Mecharyry](https://github.com/Mecharyry))
[SDK-4052]: https://auth0team.atlassian.net/browse/SDK-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

afpi: release v1.2.0

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.lock
auth0_flutter/pubspec.yaml

This release adds official support for the Web platform! 🎉 Please checkout [the readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) for full usage instructions for all supported platforms:
Other changes in this release:
**Added**
- Add support for requesting MFA challenges [SDK-4052] [\#251](https://github.com/auth0/auth0-flutter/pull/251) ([Widcket](https://github.com/Widcket))
**Fixed**
- Use Locale.US for Android [\#238](https://github.com/auth0/auth0-flutter/pull/238) ([Mecharyry](https://github.com/Mecharyry))
[SDK-4052]: https://auth0team.atlassian.net/browse/SDK-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

af: release 1.2.0

---

.github/ISSUE_TEMPLATE/Bug Report.yml

This PR updates the "Bug Report" issue form by marking the **Platform version(s)** field as **not required**, because it's not needed for the web platform.

Mark the platform version field in the "Bug Report" issue form as not required

---

auth0_flutter/.shiprc
auth0_flutter/example/ios/Runner.xcodeproj/project.pbxproj
auth0_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

This PR adds the `dart pub upgrade auth0_flutter_platform_interface` command to `auth0_flutter`'s Ship config file, as part of the `prebump` hook, so it gets automatically updated as part of the release process.
Also, automatic updates/changes to autogenerated files were included in this PR.

af: Add command for updating `afpi` to `af` Ship config

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.lock
auth0_flutter/pubspec.yaml

**Fixed**
- af: Fix email verified type [\#309](https://github.com/auth0/auth0-flutter/pull/309) ([itome](https://github.com/itome))

Release af-v1.3.1

---

.github/workflows/main.yml
auth0_flutter/android/.gitignore
auth0_flutter/android/build.gradle
auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/CredentialsManagerMethodCallHandler.kt
auth0_flutter/example/android/app/build.gradle
auth0_flutter/example/android/build.gradle

This PR uses Kotlin's own [Kover](https://github.com/Kotlin/kotlinx-kover) to generate the coverage reports for the native Kotlin code, and removes JaCoCo.

Replace JaCoCo with Kover

---

auth0_flutter/FAQ.md

This PR updates the FAQ to remove mentions of iOS 12, now that the SDK no longer supports iOS 12.

Update FAQ to remove mentions of iOS 12

---

.githooks/pre-commit
DEVELOPMENT.md
scripts/generate-symlinks.sh

This PR adds a pre-commit Git hook to aid the maintenance of the [symlinks](https://github.com/auth0/auth0-flutter/pull/350) in the `ios` and `macos` directories.
Also, the instructions in `DEVELOPMENT.md` were updated accordingly.
The hook was tested manually.

af: Add Git hook for future iOS/macOS file changes  [SDK-4698]

---

.githooks/pre-commit
.github/workflows/check-symlinks.yml

This PR updates the Git diff filter used on the Git hook and the respective CI check to include modified files, so it catches changes made to the copied files: `.gitignore` and `Podspec`.

Include modified files in `--diff-filter`

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.yaml

**Added**
- Add support for passing parameters onLoad [\#363](https://github.com/auth0/auth0-flutter/pull/363) ([frederikprijck](https://github.com/frederikprijck))
**Changed**
- Remove and gitignore `pubspec.lock` files [\#340](https://github.com/auth0/auth0-flutter/pull/340) ([Widcket](https://github.com/Widcket))

Release af-v1.4.0

---

auth0_flutter/.shiprc
auth0_flutter/pubspec.yaml

This PR updates the version of `auth0_flutter_platform_interface` in `auth0_flutter` to the latest version, and adds `--tighten` to the update command in the `.shiprc` file to make sure it's always updated when making a new release.
Fixes https://github.com/auth0/auth0-flutter/issues/368

Update `auth0_flutter_platform_interface` to 1.4.0

---

.github/dependabot.yml

This PR adds Dependabot config for updating the dependencies of the Dart packages and the example app.

Add Dependabot config for Dart packages

---

auth0_flutter/CHANGELOG.md
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/pubspec.yaml

**Fixed**
- af: Install Kover from the library's Gradle config [\#372](https://github.com/auth0/auth0-flutter/pull/372) ([Widcket](https://github.com/Widcket))
- Update `auth0_flutter_platform_interface` to 1.4.0 [\#370](https://github.com/auth0/auth0-flutter/pull/370) ([Widcket](https://github.com/Widcket))

Release af-v1.4.1

---

README.md
auth0_flutter/EXAMPLES.md
auth0_flutter/FAQ.md
auth0_flutter/README.md
auth0_flutter/example/README.md

This PR updates all the Markdown documentation (READMEs, FAQ, and EXAMPLES) to include macOS. Also a now-obsolete section was removed.

Update Markdown documentation [SDK-4705]

---

auth0_flutter/lib/src/mobile/web_authentication.dart
auth0_flutter_platform_interface/lib/src/credentials-manager/options/local_authentication.dart

This PR updates the API docs to mention macOS.

Update API docs [SDK-4740]

---

auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/macos/auth0_flutter.podspec

This PR updates the version number in the `darwin` and `macos` Podspec to match the version in the `ios` one.

af: Update version number in Podspecs

---

auth0_flutter/CHANGELOG.md
auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/macos/auth0_flutter.podspec
auth0_flutter/pubspec.yaml

**Added**
- Add support for macOS [\#381](https://github.com/auth0/auth0-flutter/pull/381) ([Widcket](https://github.com/Widcket))

Release af-v1.5.0

---

auth0_flutter/CHANGELOG.md
auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/macos/auth0_flutter.podspec
auth0_flutter/pubspec.yaml

**Added**
- Add support for HTTPS redirect URLs [SDK-4754] [\#417](https://github.com/auth0/auth0-flutter/pull/417) ([Widcket](https://github.com/Widcket))
[SDK-4754]: https://auth0team.atlassian.net/browse/SDK-4754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

af: Release af-v1.6.0

---

.github/actions/setup-darwin/action.yml

* Upgraded setup-ruby action version to 1.176.0 to include ruby version 3.0.7
[auth0/auth0-flutter/actions/runs/9014741493](https://github.com/auth0/auth0-flutter/actions/runs/9014741493/job/24776831167)

ci: upgraded setup-ruby action version to 1.176.0

---

auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/macos/auth0_flutter.podspec

Upgraded dependency on Auth0.swift to 2.7.2 to fix various issues listed in references section below
[auth0/Auth0.swift#822](https://github.com/auth0/Auth0.swift/issues/822)
[auth0/Auth0.swift#827](https://github.com/auth0/Auth0.swift/issues/827)
[auth0/Auth0.swift/pulls/850](https://github.com/auth0/Auth0.swift/pull/850)
Since, this is just a version upgrade of Auth0.swift and no other changes involved on the Flutter side, CI checks should be good enough.

(af) chore: upgraded dependency on Auth0.swift to 2.7.2

---

auth0_flutter/CHANGELOG.md
auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/macos/auth0_flutter.podspec
auth0_flutter/pubspec.yaml

**Fixed**
- (af) chore: upgraded dependency on Auth0.swift to 2.7.2 [\#451](https://github.com/auth0/auth0-flutter/pull/451) ([desusai7](https://github.com/desusai7))
- ci: upgraded setup-ruby action version to 1.176.0 [\#452](https://github.com/auth0/auth0-flutter/pull/452) ([desusai7](https://github.com/desusai7))

Release af-v1.7.2

---

.github/workflows/rl-scanner.yml

This change ensure the RL check is done when a TAG is pushed on GH for flutter release

Changed the RL work flow check

---

auth0_flutter/CHANGELOG.md
auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/macos/auth0_flutter.podspec
auth0_flutter/pubspec.yaml

**Added**
- feat: Added support for passwordless authentication [\#503](https://github.com/auth0/auth0-flutter/pull/503) ([pmathew92](https://github.com/pmathew92))
- build(deps): bump actions/download-artifact from 4.1.7 to 4.1.8 [\#499](https://github.com/auth0/auth0-flutter/pull/499) ([dependabot[bot]](https://github.com/apps/dependabot))
**Changed**
- Updated the android gradle version [\#490](https://github.com/auth0/auth0-flutter/pull/490) ([pmathew92](https://github.com/pmathew92))
- Update Swift dependencies [\#493](https://github.com/auth0/auth0-flutter/pull/493) ([Widcket](https://github.com/Widcket))
- Minor readme update [\#483](https://github.com/auth0/auth0-flutter/pull/483) ([pmathew92](https://github.com/pmathew92))
- Set `compileSdk` to `34` to match Auth0.Android …

Release af-v1.8.0

---

.github/actions/rl-scanner/action.yml
.github/actions/setup-android/action.yml
.github/actions/setup-darwin/action.yml
.github/actions/setup-publish/action.yml
.github/dependabot.yml
.github/workflows/main.yml
.github/workflows/rl-scanner.yml

This PR configures Dependabot so that all the actions used inside composite actions get automatically updated. Dependabot does not update these by default.
Also, all the actions used in composite actions were updated and pinned to a specific commit –except those official actions by Github, which don't get pinned to a commit– according to our current best practices.
See https://github.com/dependabot/dependabot-core/issues/6704

Configure Dependabot to update dependencies in composite actions

---

.github/workflows/publish-af.yml
.github/workflows/publish-afpi.yml

This PR re enables the reversing labs security checks for  before publishing

Re enabling the reversing labs workflow

---

auth0_flutter_platform_interface/CHANGELOG.md
auth0_flutter_platform_interface/pubspec.yaml

**Added**
- Added support for WASM compilation [\#516](https://github.com/auth0/auth0-flutter/pull/516) ([pmathew92](https://github.com/pmathew92))
**Updated**
- Updated Flutter version to 3.24.0 ([pmathew92](https://github.com/pmathew92))
- Updated Dart sdk version to 3.5.0 ([pmathew92](https://github.com/pmathew92))

Release afpi-v1.9.0

---

auth0_flutter/CHANGELOG.md
auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/macos/auth0_flutter.podspec
auth0_flutter/pubspec.yaml

**Added**
- Added support for WASM compilation [\#516](https://github.com/auth0/auth0-flutter/pull/516) ([pmathew92](https://github.com/pmathew92))
- af: Ignore locale when it's not a string [\#518](https://github.com/auth0/auth0-flutter/pull/518) ([Widcket](https://github.com/Widcket))
**Updated**
- Updated Flutter version to 3.24.0 ([pmathew92](https://github.com/pmathew92))
- Updated Dart sdk version to 3.5.0 ([pmathew92](https://github.com/pmathew92))

Release af-v1.9.0

---

auth0_flutter/CHANGELOG.md
auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/macos/auth0_flutter.podspec
auth0_flutter/pubspec.yaml

**Added**
- implement app state getter for web [\#509](https://github.com/auth0/auth0-flutter/pull/509) ([navaronbracke](https://github.com/navaronbracke))
- feat(auth): 🔐 Add UserProfile serialization and include in Credentials [\#556](https://github.com/auth0/auth0-flutter/pull/556) ([Rohithgilla12](https://github.com/Rohithgilla12))
**Fixed**
- Fixed the WASM compilation issue on 3.24 version of flutter [\#547](https://github.com/auth0/auth0-flutter/pull/547) ([pmathew92](https://github.com/pmathew92))

Release af-v1.10.0

---

auth0_flutter/CHANGELOG.md
auth0_flutter/darwin/auth0_flutter.podspec
auth0_flutter/ios/auth0_flutter.podspec
auth0_flutter/lib/src/version.dart
auth0_flutter/macos/auth0_flutter.podspec
auth0_flutter/pubspec.yaml

**Added**
- Added support to configure credentials manager for iOS and Android  [\#576](https://github.com/auth0/auth0-flutter/pull/576) ([pmathew92](https://github.com/pmathew92))

Release af-v1.11.0

---

auth0_flutter/CHANGELOG.md
auth0_flutter_platform_interface/CHANGELOG.md

This PR updates the minimum iOS version required in the change log

Added minimum iOS version in the change log

---

.github/actions/setup-android/action.yml
.github/workflows/main.yml

chore(CI) : Fixing the gradle error issue on Android UT pipeline

---

.github/workflows/claude-code-review.yml

This PR adds a new GitHub Actions workflow for automated code review using `pr-analyser`.
- Added a new GitHub Actions workflow file `.github/workflows/claude-code-review.yml`
- The workflow is triggered on:
- Issue comments creation (`issue_comment.types: [created]`)
- Pull request review comments creation (`pull_request_review_comment.types: [created]`)
- Configured necessary permissions:
- `contents: write` - to read repository content
- `issues: write` - to interact with issues
- `pull-requests: write` - to comment on pull requests
- `id-token: write` - for authentication
- Uses the reusable workflow from `auth0/auth0-ai-pr-analyzer-gh-action/.github/workflows/claude-code-review.yml@main`

Adds claude-code-review github workflow
